SELECT C.SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES AS B
JOIN (SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE
     FROM HR_GRADE
     WHERE YEAR = 2022
     GROUP BY EMP_NO) AS C
     ON B.EMP_NO = C.EMP_NO
WHERE C.SCORE = (SELECT MAX(TOTAL_SCORE)
               FROM (SELECT SUM(SCORE) AS TOTAL_SCORE
                     FROM HR_GRADE
                     WHERE YEAR =2022
                     GROUP BY EMP_NO) AS T)

               